name: Dispatch
run-name: Dispatched Repository Actions - ${{ inputs.job }} ⌛️
on:
  workflow_dispatch:
    inputs:
      job:
        description: Dispatch job to run
        required: true
        type: choice
        options:
          - build
          - macos
permissions:
  contents: write
jobs:
  check-and-build:
    if: inputs.job == 'build'
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit

  macos-build:
    name: Build for macOS 🍏
    if: inputs.job == 'macos'
    runs-on: macos-15
    defaults:
      run:
        shell: zsh --no-rcs --errexit --pipefail {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set Up Environment 🔧
        id: setup
        run: |
          : Set Up Environment 🔧
          if (( ${+RUNNER_DEBUG} )) setopt XTRACE

          print '::group::Enable Xcode 16.1'
          sudo xcode-select --switch /Applications/Xcode_16.1.0.app/Contents/Developer
          print '::endgroup::'

          local product_name
          local product_version
          local commit_hash="${GITHUB_SHA:0:9}"
          read -r product_name product_version <<< \
            "$(jq -r '. | {name, version} | join(" ")' buildspec.json)"

          print "pluginName=${product_name}" >> $GITHUB_OUTPUT
          print "pluginVersion=${product_version}" >> $GITHUB_OUTPUT
          print "commitHash=${commit_hash}" >> $GITHUB_OUTPUT

      - uses: actions/cache/restore@v4
        id: ccache-cache
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-RelWithDebInfo
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Build Plugin 🧱
        uses: ./.github/actions/build-plugin
        with:
          target: macos-universal
          config: RelWithDebInfo
          codesign: false

      - name: Package Plugin 📀
        uses: ./.github/actions/package-plugin
        with:
          target: macos-universal
          config: RelWithDebInfo
          package: false
          codesign: false
          notarize: false

      - name: Upload Artifacts 📡
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-macos-universal-${{ steps.setup.outputs.commitHash }}
          path: ${{ github.workspace }}/release/${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-macos-universal.*
